### ISSUE TITLE
Error when installing on Symfony 7

### ISSUE THREAD

**Issue by pbowyer** [jolicode/automapper-bundle#8]
On a new Symfony 7 project, `composer require` works until we reach "Executing script cache:clear" and then fails with:
> In CheckExceptionOnInvalidReferenceBehaviorPass.php line 85:
> The service "automapper.property_info.cache.inner" has a dependency on a non-existent service "property_info.phpstan_extractor". Did you mean one of these: "property_info.serializer_extractor", "property_info.reflection_extractor"?

This turns out to be an error Google knows nothing about :) 

Tested with bundle versions `v8.0.2` and `dev-main 9c51bde`

**Comment by Korbeil** [comment]
Hey @pbowyer, how did you install `serializer` within your Symfony installation ?
Normally, you should use `symfony/serializer-pack` that includes both of theses packages :thinking: 

I don't think it should be AutoMapper's responsability to require that :confused:

**Comment by pbowyer** [comment]
Hi @Korbeil I thought automapper was an alternative to Symfony's serializer? The Quick Start says install `composer require jolicode/automapper-bundle` so I hadn't installed `symfony/serializer-pack`.

If you need that, it explains why the dependencies weren't there 😄

**Comment by Korbeil** [comment]
Thanks for the feedback, you're totally right, I made a PR to fix this :+1:
